{{- if .Values.halyard.gitops.enabled }}
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://{{ .Values.halyard.gitops.repo.username }}:{{ urlquery (tpl "{{ .Values.halyard.gitops.repo.token }}" .) }}@{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.repository }}.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.dynamicAccRepository }}.git
  gituser: {{ .Values.halyard.gitops.repo.username }}
  gittoken: {{ .Values.halyard.gitops.repo.token }}
  dynamicAccRepository: {{ .Values.halyard.gitops.repo.dynamicAccRepository }}

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
{{- end }}
