{{ if .Values.halyard.gitops.enabled }}
{{- if (eq .Values.halyard.gitops.secretName "opsmx-gitops-auth") }}
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  {{- if (eq .Values.halyard.gitops.repo.type "git") }}
  gitcloneparam: https://{{ .Values.halyard.gitops.repo.username }}:{{ urlquery (tpl "{{ .Values.halyard.gitops.repo.token }}" .) }}@{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.repository }}.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.dynamicAccRepository }}.git
  gituser: {{ .Values.halyard.gitops.repo.username }}
  gittoken: {{ .Values.halyard.gitops.repo.token }}
  dynamicAccRepository: {{ .Values.halyard.gitops.repo.dynamicAccRepository }}
  {{- end }}

  {{- if (eq .Values.halyard.gitops.repo.type "stash") }}
  {{- if (eq .Values.halyard.gitops.repo.projectName "") }}
  gitcloneparam: https://{{ .Values.halyard.gitops.repo.username }}:{{ urlquery (tpl "{{ .Values.halyard.gitops.repo.token }}" .) }}@{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.repository }}.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.dynamicAccRepository }}.git
  gituser: {{ .Values.halyard.gitops.repo.username }}
  gittoken: {{ .Values.halyard.gitops.repo.token }}
  {{- else if (ne .Values.halyard.gitops.repo.projectName "") }}
  gitcloneparam: https://{{ .Values.halyard.gitops.repo.username }}:{{ urlquery (tpl "{{ .Values.halyard.gitops.repo.token }}" .) }}@{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.projectName }}/{{ .Values.halyard.gitops.repo.repository }}.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://{{ .Values.halyard.gitops.repo.baseUrlHostName }}/{{ .Values.halyard.gitops.repo.organization }}/{{ .Values.halyard.gitops.repo.projectName }}/{{ .Values.halyard.gitops.repo.dynamicAccRepository }}.git
  gituser: {{ .Values.halyard.gitops.repo.username }}
  gittoken: {{ .Values.halyard.gitops.repo.token }}
  dynamicAccRepository: {{ .Values.halyard.gitops.repo.dynamicAccRepository }}
  {{- end }}
  {{- end }}

  {{- if (eq .Values.halyard.gitops.repo.type "s3") }}
  s3accesskey: {{ .Values.halyard.gitops.repo.s3accesskey }}
  s3secretkey: {{ .Values.halyard.gitops.repo.s3secretkey }}
  s3bucket: {{ .Values.halyard.gitops.repo.s3bucket }}
  s3region: {{ .Values.halyard.gitops.repo.s3region }}
  {{- end }}

kind: Secret
metadata:
  name: {{ .Values.halyard.gitops.secretName }}
type: Opaque
{{- end -}}
{{ end }}
