dependencies:
- name: redis
  version: 10.5.3
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 8.0.9
  repository: https://helm.min.io/
  condition: minio.enabled
