{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "spinnaker.fullname" . }}-deck
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      {{- if index $.Values.ingress "annotations" }}
      {{- if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" "nsx" }}
      - path: /*
      {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
      - path: /
      {{- end }}
      {{- else}}{{/* Has no annotations */}}
      - path: /
      {{- end }}
        {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: spin-deck
            port:
              number: 9000
          {{- else }}
          serviceName: spin-deck
          servicePort: 9000
          {{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
